"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
## add lines to make use of python-dotenv package: pip install python-dotenv
import os
from dotenv import load_dotenv
load_dotenv()

# some settings are required only for development
IS_DEVELOPMENT = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    ## add humanize package
    'django.contrib.humanize',
]

APPLICATION_APPS = [
    # project apps
    'questionaires.apps.QuestionairesConfig',
    'questionaire_answers.apps.QuestionaireAnswersConfig',
    'investment_types.apps.InvestmentTypesConfig',
    'investment_choices.apps.InvestmentChoicesConfig',
    'investment_datas.apps.InvestmentDatasConfig',
    'user_investments.apps.UserInvestmentsConfig',
    'user_questionaire_answers.apps.UserQuestionaireAnswersConfig',
    'pages.apps.PagesConfig',
]

THIRD_PARTY_APPS = [
    'widget_tweaks',
    'taggit',
]

DEBUG_APPS = [
    "debug_toolbar",
]

if IS_DEVELOPMENT:
    ### development apps
    INSTALLED_APPS = DJANGO_APPS + APPLICATION_APPS + THIRD_PARTY_APPS + DEBUG_APPS
else:
    ### deployment apps
    INSTALLED_APPS = DJANGO_APPS + APPLICATION_APPS + THIRD_PARTY_APPS

# end Application definition


# Middleware definition

DEBUG_MIDDLEWARE = [
    # for django debug toolbar:
    # The order of MIDDLEWARE is important. You should include the Debug Toolbar middleware as early as possible in the list. However, it must come after any other middleware that encodes the response’s content, such as GZipMiddleware.
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

DJANGO_MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if IS_DEVELOPMENT:
    ### development middleware
    MIDDLEWARE = DEBUG_MIDDLEWARE + DJANGO_MIDDLEWARE
else:
    ### deployment middleware
    MIDDLEWARE = DJANGO_MIDDLEWARE

# end Middleware definition


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE'    : os.getenv('PDB_ENGINE'),
        'NAME'      : os.getenv('PDB_NAME'),
        'USER'      : os.getenv('PDB_USER'),
        'PASSWORD'  : os.getenv('PDB_PASSWORD'),
        'HOST'      : os.getenv('PDB_HOST'),
        'PORT'      : os.getenv('PDB_PORT'),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



## add a location for photos jpg files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


### The Debug Toolbar is shown only if your IP address is listed in Django’s INTERNAL_IPS setting. This means that for local development, you must add "127.0.0.1" to INTERNAL_IPS. You’ll need to create this setting if it doesn’t already exist in your settings module:
INTERNAL_IPS = [
    "127.0.0.1",
]

### add message tags to match bootstrap classes
from django.contrib.messages import constants as djmsg_const
MESSAGE_TAGS = {
    djmsg_const.ERROR   : 'danger',
    djmsg_const.DEBUG   : 'secondary',
    djmsg_const.INFO    : 'info',
    djmsg_const.SUCCESS : 'success',
    djmsg_const.WARNING : 'warning',
}


### email backend
### https://docs.djangoproject.com/en/6.0/topics/email/
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASS')


# End of settings.py

